version: '3.6'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: superuser
      POSTGRES_DB: main
    ports:
      - 5656:5432
    volumes:
      - ./docker/volumes/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9998:8080
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: postgres